name: "Release Published to Discord"
on:
  release:
    types: [published]

jobs:
  publish-maven:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Set up JDK 21
        uses: actions/setup-java@v4
        with:
          java-version: '21'
          distribution: 'temurin'

      - name: Make gradlew executable
        run: chmod +x gradlew

      - name: Build and publish to GitHub Packages
        env:
          GITHUB_TOKEN: ${{ secrets.RELEASE_TOKEN }}
          GITHUB_ACTOR: ${{ github.actor }}
          TAG: ${{ github.event.release.tag_name }}
        run: ./gradlew build devJar publish